// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grytmqsuxcdddvbpyfcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyeXRtcXN1eGNkZGR2YnB5ZmN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NDE4MTMsImV4cCI6MjA3NDIxNzgxM30.GQssu7lpbnPFsWgXy1eatKlnqix8UgfmW6AesH6lD4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});